options:
  merge-default-rules: false
rules:
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-line-between-blocks:
    - 1
    -
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  hex-length: 2
  hex-notation:
    - 1
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-trailing-whitespace: 2
  no-universal-selectors: 2
  one-declaration-per-line: 2
  property-sort-order: 1
  quotes: 1
  shorthand-values: 2
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
  zero-unit: 2